changelog:
  exclude:
    labels:
      - 'ignore'
    authors:
      - 'dependabot[bot]'
  categories:
    - title: 'Added'
      labels:
        - 'enhancement'
        - 'feature'
        - 'feat'
    - title: 'Fixed'
      labels:
        - 'bug'
        - 'fix'
    - title: 'Changed'
      labels:
        - 'changed'
        - 'refactor'
    - title: 'Maintenance'
      labels:
        - 'chore'
        - 'ci'
        - 'dependencies'
